services:
  - type: web
    name: discount-pro
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    healthCheckPath: /up
    preDeployCommand: php artisan migrate --force
    envVars:
      - key: APP_NAME
        value: Discount Pro
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: APP_MAINTENANCE_DRIVER
        value: file
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: mongodb
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
      - key: SESSION_ENCRYPT
        value: false
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: file
      - key: VITE_APP_NAME
        value: Discount Pro
      - key: SUPER_ADMIN_SECRET_KEY
        sync: false